### PR TITLE
Fix the XMPP reconnection issues

### LINKED ISSUE #41: Doesn't properly reconnect after proper server disconnection
1. Start Emulsion, connect to XMPP server
2. Shut down the server (Prosody in my case)
3. The server will properly close the XML stream
4. But the client won't detect it

The reason is in this line of code: https://github.com/vitalyster/SharpXMPP/blob/6a187edbe8b6ebf93c90dd10c622f944419e407f/SharpXMPP.Shared/XmppTcpConnection.cs#L79

Prosody closes the XML correctly, thus it will just start returning `false` in loop instead of trying to read more from the stream and failing.

### LINKED ISSUE #42: Doesn't properly reconnect after network outage
Currently test from #17 doesn't work for one small reason: we use the 0.0.1 version of SharpXMPP which exposes the `async void Connect` method: https://github.com/vitalyster/SharpXMPP/blob/5db7e955fa6d7a679daf8399e86b44acd3ac45e0/SharpXMPP.Shared/XmppTcpConnection.cs#L124

An asynchronous error in the `async void` methods kills the application.

We need to migrate to a newer library version which exposes the same method as `Task`.

### PR DESCRIPTION
**Pull request by ForNeVeR**
This PR updates the SharpXMPP library to the newly released version 0.0.2.

In that release, I've fixed a couple of bugs, and the library API has been updating.

Impact:

- closes #41 (because of https://github.com/vitalyster/SharpXMPP/pull/22)
- closes #42 (because the API no more uses an `async void` horror from C#)
- somewhat improves the situation around #55 (throws proper exceptions when the client is know to be inactive instead of losing the messages)
- will improve the SharpXMPP error logging after we implement #16 (because of proper inner exception handling)

### CODE REVIEW

File: Emulsion/Xmpp/Client.fs [hunk 1]
```diff
@@ -8,11 +8,21 @@ open Emulsion.Settings
...
 type Client(ctx: RestartContext, cancellationToken: CancellationToken, settings: XmppSettings) =
     inherit MessageSystemBase(ctx, cancellationToken)
-    let client = XmppClient.create settings
 
-    override __.RunUntilError receiver =
-        XmppClient.run settings client receiver
+    let client = ref None
+
+    override __.RunUntilError receiver = async {
+        use newClient = XmppClient.create settings receiver
```
Comment (ForNeVeR) [inline Emulsion/Xmpp/Client.fs]: Raise a separate issue about that case.

Let's use `JetBrains.Dataflow.Lifetime` here to prevent the following case:
1. Thread 1 performs `Volatile.Read` (and reads the "good" client)
2. Thread 2 performs `Volatile.Write(None)`
3. Thread 1 starts to perform some calls on the `client`
4. Thread 2 at the same time calls `client.Dispose()`

As the result, `client` could become disposed in parallel with some calls by thread 1, which is very bad (at least theoretically). It is in my opinion worse than any calls on a non-disposed client (even if it has already failed).

Here we should use the `lifetime` pattern and `lifetime.Using`, and instead of `Volatile.Read` we better call `lifetime.ExecuteIfAlive` that should prevent us from disposing a lifetime that has some ongoing calls on it.

**Comment by ForNeVeR** [comment]
Thanks for review!

File: Emulsion/Xmpp/Client.fs (hunk 1 above)
Comment (ForNeVeR) [reply Emulsion/Xmpp/Client.fs]: → #62
